//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmployee
    {
        public int UserID { get; set; }
        public string NameSurname { get; set; }
        public string Email { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Username { get; set; }
        public string Pasword { get; set; }
        public int HotelFloor { get; set; }
        public string Gender { get; set; }
        public string Citizenship { get; set; }
        public string Engagment { get; set; }
        public int Salary { get; set; }
        public int EmployeeID { get; set; }
    }
}
